### ISSUE TITLE
API auth

### ISSUE THREAD

**Issue by magenx** [Simicart/SimiCart-Magento2.x#40]
please confirm issue sent to your email
any solution or way to fix this problem.

**Comment by crabbynguyen** [comment]
Hi,
Thanks for your response. If you want to enable authorization for API, please remove comment from line 46-69 in this file:

https://github.com/Simicart/SimiCart-Magento2.x/blob/master/app/code/Simi/Simiconnector/Controller/Rest/Action.php

Hope this help!

**Comment by magenx** [comment]
why the API working by default without authorization or token ??

**Comment by crabbynguyen** [comment]
As you can see in our comment, we need to disable it by default to submit package to Magento Marketplace. Otherwise, they will reject this extension.
